#!/bin/bash
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.0 --aug2 0.1 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.2 --aug2 0.2 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.3 --aug2 0.3 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.4 --aug2 0.4 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.5 --aug2 0.5 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.6 --aug2 0.6 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.7 --aug2 0.7 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.8 --aug2 0.8 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.9 --aug2 0.9 

python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.1 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.2 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.3 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.4 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.5 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.6 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.7 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.8 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.9 --aug2 0.0 

python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.1 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.2 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.3 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.4 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.5 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.6 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.7 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.8 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset squirrel --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.9 

python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.0 --aug2 0.1 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.2 --aug2 0.2 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.3 --aug2 0.3 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.4 --aug2 0.4 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.5 --aug2 0.5 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.6 --aug2 0.6 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.7 --aug2 0.7 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.8 --aug2 0.8 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.9 --aug2 0.9 

python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.1 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.2 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.3 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.4 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.5 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.6 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.7 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.8 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.9 --aug2 0.0 

python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.1 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.2 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.3 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.4 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.5 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.6 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.7 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.8 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset texas --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.9 

python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.0 --aug2 0.1 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.2 --aug2 0.2 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.3 --aug2 0.3 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.4 --aug2 0.4 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.5 --aug2 0.5 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.6 --aug2 0.6 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.7 --aug2 0.7 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.8 --aug2 0.8 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.9 --aug2 0.9 

python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.1 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.2 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.3 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.4 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.5 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.6 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.7 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.8 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.9 --aug2 0.0 

python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.1 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.2 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.3 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.4 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.5 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.6 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.7 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.8 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset chameleon --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.9 

python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.0 --aug2 0.1 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.2 --aug2 0.2 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.3 --aug2 0.3 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.4 --aug2 0.4 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.5 --aug2 0.5 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.6 --aug2 0.6 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.7 --aug2 0.7 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.8 --aug2 0.8 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.9 --aug2 0.9 


python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.1 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.2 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.3 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.4 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.5 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.6 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.7 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.8 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.9 --aug2 0.0 

python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.1 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.2 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.3 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.4 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.5 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.6 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.7 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.8 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.9 

python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.0 --aug2 0.1 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.2 --aug2 0.2 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.3 --aug2 0.3 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.4 --aug2 0.4 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.5 --aug2 0.5 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.6 --aug2 0.6 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.7 --aug2 0.7 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.8 --aug2 0.8 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side both --aug 0.9 --aug2 0.9 

python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.1 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.2 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.3 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.4 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.5 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.6 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.7 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.8 --aug2 0.0 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side high --aug 0.9 --aug2 0.0 

python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.1 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.2 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.3 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.4 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.5 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.6 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.7 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.8 
python MIX_FBGCN_AUG_EA.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 --second_hidden_dim 256 --aug_type EA  --aug_side low --aug 0.0 --aug2 0.9 
