#!/bin/bash
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 0  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 0  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 50  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 50  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 100  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 100  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 150  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 150  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 250  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 250  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 300  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type True --preepochs 300  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type False --preepochs 0  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type False --preepochs 0  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type False --preepochs 50  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type False --preepochs 50  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type False --preepochs 150  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type False --preepochs 150  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type False --preepochs 250  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type False --preepochs 250  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type False --preepochs 300  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset cora --pre_learning_rate 0.0005 --loss_type False --preepochs 300  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type True --preepochs 0  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type True --preepochs 0  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type True --preepochs 50  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type True --preepochs 50  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type True --preepochs 100  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type True --preepochs 100  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type True --preepochs 150  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type True --preepochs 150  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type True --preepochs 200  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type True --preepochs 250  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type True --preepochs 250  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type True --preepochs 300  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type True --preepochs 300  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 0  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 0  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 50  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 50  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 100  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 150  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 150  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 200  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 250  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 250  --hidden_dim 256 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 300  --hidden_dim 128 
python train.py --config ./configs/fbgcn.json --dataset citeseer --pre_learning_rate 0.0005 --loss_type False --preepochs 300  --hidden_dim 256 
